name: vgc_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - bioconda::entrez-direct=16.2
  - ffq
  - sra-tools=3.1.1
  - snakemake=5.26.0
  - ncbi-datasets-cli=14.6.0
  - coreutils
  - hisat2=2.2.1
  - fastp=0.23.2
  - samtools=1.16.1
  - spades=3.15.5
  - seqkit
  - diamond
